name: Build image using alpine 3.18+ nightly using latest v2

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DOCKER_USERNAME: theidledeveloper

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: [3.18, 3.19]
    steps:
      - uses: actions/checkout@v4

      - name: Container Details
        id: container_detail
        run: |
          TAG=v2

          # Use the repository name as the image name for simplicity
          IMAGE_NAME="$(echo ${GITHUB_REPOSITORY} | cut -d: -f1)"
          IMAGE_TAG="${TAG}-nightly"

          TAGS="${IMAGE_NAME}:${IMAGE_TAG},${IMAGE_NAME}:${IMAGE_TAG}-alpine${{ matrix.alpine_version }}"

          # Set output parameters.
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "aws_cli_version=2" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            AWS_CLI_VERSION=${{ steps.container_detail.outputs.aws_cli_version }}
          file: ./Dockerfile.native
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.container_detail.outputs.tags }}
